### ISSUE TITLE
Regularly crashing :(

### ISSUE THREAD

**Issue by gerroon** [Erikvl87/docker-languagetool#23] opened 2021-07-24 07:37 UTC
Debian Testing X64, Docker Run

```
docker run  -d --name=languagetool \
        --restart unless-stopped \
        -e langtool_languageModel=/ngrams \
        -e Java_Xmx=1400m \
        --memory 1024m --memory-swap 1300m \
        -e EXTRAOPTIONS="-Xmx582M" \
        -v /media//languagetool/ngram:/ngrams \
        -p 8010:8010 \
        erikvl87/languagetool

```

```

2021-07-23 08:05:15.639 +0000 WARN  org.languagetool.language.LanguageIdentifier Cannot consider noopLanguages because not in fastText mode: [en, es]                                                                                         
2021-07-23 08:06:30.277 +0000 INFO  org.languagetool.server.TextChecker Check done: 278 chars, en-US[auto], requestId: null, #279, null, 2 matches, 2339632ms, agent:webextension-chrome-ng, v:4.0.7, sent, q:112, h:10, dH:1, m:!tlo         
2021-07-23 08:06:30.280 +0000 WARN  org.languagetool.language.LanguageIdentifier Cannot consider noopLanguages because not in fastText mode: [en, es]                                                                                         
2021-07-23 08:06:30.367 +0000 INFO  org.languagetool.server.TextChecker Check done: 365 chars, en-US[auto], requestId: null, #280, null, 0 matches, 89ms, agent:webextension-chrome-ng, v:4.0.7, sent, q:111, h:10, dH:1, m:tlo               
2021-07-23 08:06:30.369 +0000 WARN  org.languagetool.language.LanguageIdentifier Cannot consider noopLanguages because not in fastText mode: [en, es]                                                                                         
2021-07-23 08:11:07.448 +0000 INFO  org.languagetool.server.TextChecker Check done: 278 chars, en-US[auto], requestId: null, #276, null, 2 matches, 2439416ms, agent:webextension-chrome-ng, v:4.0.7, sent, q:112, h:10, dH:1, m:!tlo         
2021-07-23 08:11:07.450 +0000 WARN  org.languagetool.language.LanguageIdentifier Cannot consider noopLanguages because not in fastText mode: [en, es]
2021-07-23 08:16:02.186 +0000 INFO  org.languagetool.server.TextChecker Check done: 366 chars, en-US[auto], requestId: null, #277, null, 0 matches, 294737ms, agent:webextension-chrome-ng, v:4.0.7, notSent: Broken pipe, q:112, h:10, dH:1, 
m:tlo
2021-07-23 08:16:35.247 +0000 WARN  org.languagetool.language.LanguageIdentifier Cannot consider noopLanguages because not in fastText mode: [en, es]
start.sh: line 18:     8 Killed                  java -Xms$Xms -Xmx$Xmx -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8010 --public --allow-origin '*' --config config.properties
```

**Comment by Erikvl87** [comment] 2021-07-31 10:45
Could you give me some more details on how to reproduce? I've just ran a Debian 64bit VM but couldn't reproduce your findings.

- What is the request that you execute?
    - Which configuration parameters are included in that request? 
- Does it matter which text is being checked?
- How often do you encounter this error?
- Do you use ngrams?
    - Which datasets are included?

**Comment by gerroon** [comment] 2021-07-31 16:19
Hi

Thanks for pointing out the issues with my config. I guess I did not know what I was doing given my understanding of Java is just zero.  

I fixed my conf based on your points and so far it is going well.

**Comment by Erikvl87** [comment] 2021-08-01 07:49
That's great! I'll close this issue. 

Please leave a comment in here if you re encounter the same issue so we can reopen this issue.

**Closed by Erikvl87** 2021-08-01 07:49 UTC
Labels: question
